version: "3.3"

services:
  flask_web:
    build: .
    restart: always
    networks: 
      - docker_course
    ports:
      - "5000:5000"
    depends_on:
      - flask_postgres
    environment:
      FLASK_IP: ${FLASK_IP}
      FLASK_PORT: ${FLASK_PORT}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  flask_postgres:
    image: postgres
    restart: on-failure
    healthcheck:
      test: ["CMD", 'pg_isready -U postgres'] 
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    networks: 
      - docker_course

networks:
    docker_course:
        driver: bridge